export const STORY_ARCHIVE = 'STORY_ARCHIVE';
export type STORY_ARCHIVE = typeof STORY_ARCHIVE;

export const STORIES_FETCH = 'STORIES_FETCH';
export type STORIES_FETCH = typeof STORIES_FETCH;

export const STORIES_ADD = 'STORIES_ADD';
export type STORIES_ADD = typeof STORIES_ADD;

export const STORIES_FETCH_ERROR = 'STORIES_FETCH_ERROR';
export type STORIES_FETCH_ERROR = typeof STORIES_FETCH_ERROR;
